import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ApolloProvider } from "@apollo/client";
import client from "@/components/apollo/client";
import ApolloWrapper from "@/components/apollo/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Register"
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
